# Generated by Django 6.0.2 on 2026-02-14 14:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Album Title')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Release Year')),
                ('condition', models.CharField(choices=[('Mint', 'Mint (Perfect)'), ('Near Mint', 'Near Mint'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=20, verbose_name='Vinyl Condition')),
                ('speed', models.CharField(choices=[('33', '33 ⅓ RPM'), ('45', '45 RPM'), ('78', '78 RPM')], default='33', max_length=10, verbose_name='Playback Speed')),
                ('catalog_number', models.CharField(blank=True, max_length=50, verbose_name='Catalog Number')),
                ('notes', models.TextField(blank=True, verbose_name='Personal Notes')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_played', models.DateField(blank=True, null=True, verbose_name='Last Played')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist', verbose_name='Artist/Band')),
                ('genre', models.ManyToManyField(to='artists.genre', verbose_name='Genres')),
            ],
            options={
                'ordering': ['artist__name', 'release_year'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.DurationField(blank=True, help_text='Format: HH:MM:SS', null=True)),
                ('track_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='records.album')),
            ],
            options={
                'ordering': ['track_number'],
                'unique_together': {('album', 'track_number')},
            },
        ),
    ]
