# Generated by Django 6.0.2 on 2026-02-14 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full artist or band name', max_length=200, unique=True, verbose_name='Artist/Band Name')),
                ('formation_type', models.CharField(choices=[('Solo', 'Solo Artist'), ('Band', 'Band/Group'), ('Duo', 'Duo')], default='Solo', max_length=10, verbose_name='Type')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country of Origin')),
                ('formed_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Year Formed')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Genre Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
