# Generated by Django 6.0.2 on 2026-02-14 14:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporary_artist', models.CharField(blank=True, max_length=200)),
                ('album_title', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('Low', 'Low Priority'), ('Medium', 'Medium Priority'), ('High', 'High Priority'), ('Urgent', 'Urgent - Must Have!')], default='Medium', max_length=10)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.artist')),
            ],
            options={
                'ordering': ['-priority', 'album_title'],
            },
        ),
    ]
